// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8CFIM2kdjGWcY0XFI5G7qmF0Iecu3Yrs',
    appId: '1:257849877914:web:21bf1da6252c47991f0623',
    messagingSenderId: '257849877914',
    projectId: 'gemini-risk-assessor',
    authDomain: 'gemini-risk-assessor.firebaseapp.com',
    storageBucket: 'gemini-risk-assessor.appspot.com',
    measurementId: 'G-CE170DPKVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXxCnVjEp4crK0AWscaf2nDjGJ5xHkAmA',
    appId: '1:257849877914:android:1c6083731f777a581f0623',
    messagingSenderId: '257849877914',
    projectId: 'gemini-risk-assessor',
    storageBucket: 'gemini-risk-assessor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDzEt8A4NlLwRFrAZ0W51qqAEJ4THEGGU',
    appId: '1:257849877914:ios:a916a61adc6d64851f0623',
    messagingSenderId: '257849877914',
    projectId: 'gemini-risk-assessor',
    storageBucket: 'gemini-risk-assessor.appspot.com',
    iosBundleId: 'com.raphaeldaka.geminiriskassessor',
  );
}
